/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package barras;

import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author efra1323
 */
public class PantallaInicio extends javax.swing.JFrame {

    /**
     * Creates new form PantallaInicio
     */
    public PantallaInicio() {
        super("Asistencia");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnListo = new javax.swing.JButton();
        jlblNombre = new javax.swing.JLabel();
        jlblBienvenido = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtxtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtxtMatricula = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbtnListo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jbtnListo.setText("Listo");
        jbtnListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnListoActionPerformed(evt);
            }
        });

        jlblNombre.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jlblNombre.setForeground(new java.awt.Color(51, 0, 255));

        jlblBienvenido.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jlblBienvenido.setForeground(new java.awt.Color(0, 153, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnListo)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbtnListo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblBienvenido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Alumno:");

        jtxtNombre.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Matricula:");

        jtxtMatricula.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jtxtMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtMatriculaActionPerformed(evt);
            }
        });
        jtxtMatricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtMatriculaKeyPressed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton2.setText("Registrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(30, 30, 30)
                        .addComponent(jtxtNombre)))
                .addGap(10, 10, 10)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtMatriculaActionPerformed

    private void jbtnListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnListoActionPerformed
        // TODO add your handling code here:
        inicio llamada = new inicio();
        llamada.setLocationRelativeTo(this);
        llamada.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_jbtnListoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat formatoDia = new SimpleDateFormat("yyyy/MM/dd");
        String fecha = formatoDia.format(new Date());
        String asistencia ="";
        String horaMateria= BD.obtenerHoraMateria(Sesion.usuarioActual, Sesion.materiaActual);
        
        System.out.println(horaMateria);
        
        SimpleDateFormat formatoHora = new SimpleDateFormat("kk:mm");
        String hora = formatoHora.format(new Date());
        
        if(jtxtMatricula.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Ingresa datos !", "Atención", JOptionPane.WARNING_MESSAGE);
        }
        else{
            
            //System.out.println(BD.yaRegistradoLista(Sesion.materiaActual,jtxtMatricula.getText(), fecha, Sesion.usuarioActual));
            if(BD.yaRegistradoLista(Sesion.materiaActual,jtxtMatricula.getText(), fecha, Sesion.usuarioActual)){
                JOptionPane.showMessageDialog(this, "Ya registrado !", "Atención", JOptionPane.ERROR_MESSAGE);
            }
            else{
                if(BD.existeEnGrupo(jtxtMatricula.getText(), Sesion.materiaActual , Sesion.usuarioActual)){
                    BD.insertarLista(Sesion.materiaActual, jtxtMatricula.getText(), "", fecha, Sesion.usuarioActual,hora, asistencia);
                
                    this.jlblBienvenido.setText("Bienvenido ! ");
                    this.jlblNombre.setText(BD.obtenerNombAlumno(jtxtMatricula.getText()) );
                    this.jtxtMatricula.setText("");
                    this.jtxtMatricula.requestFocus();
                    
                }
                
                else{
                    JOptionPane.showMessageDialog(this, "Alumno no dado de alta en esta materia","Atención",JOptionPane.ERROR_MESSAGE);
                    this.jtxtMatricula.setText("");
                    this.jtxtMatricula.requestFocus();
                }
                
            }
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtxtMatriculaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtMatriculaKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            SimpleDateFormat formatoDia = new SimpleDateFormat("yyyy/MM/dd");
            String fecha = formatoDia.format(new Date());
            String asistencia="";
        
        SimpleDateFormat formatoHora = new SimpleDateFormat("kk:mm");
        String hora = formatoHora.format(new Date());
        
        if(jtxtMatricula.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Ingresa datos !", "Atención", JOptionPane.WARNING_MESSAGE);
        }
        else{
            
            //System.out.println(BD.yaRegistradoLista(Sesion.materiaActual,jtxtMatricula.getText(), fecha, Sesion.usuarioActual));
            if(BD.yaRegistradoLista(Sesion.materiaActual,jtxtMatricula.getText(), fecha, Sesion.usuarioActual)){
                JOptionPane.showMessageDialog(this, "Ya registrado !", "Atención", JOptionPane.ERROR_MESSAGE);
                this.jtxtMatricula.setText("");
                this.jtxtMatricula.requestFocus();
            }
            else{
                if(BD.existeEnGrupo(jtxtMatricula.getText(), Sesion.materiaActual, Sesion.usuarioActual)){
                    BD.insertarLista(Sesion.materiaActual, jtxtMatricula.getText(), "", fecha, Sesion.usuarioActual,hora,asistencia);
                    System.out.println("Bienvenido "+jtxtMatricula.getText());
                
                    
                    this.jlblBienvenido.setText("Bienvenido !");
                    this.jlblNombre.setText(BD.obtenerNombAlumno(jtxtMatricula.getText()) );
                    this.jtxtMatricula.setText("");
                    this.jtxtMatricula.requestFocus();
                    
                }
                
                else{
                    JOptionPane.showMessageDialog(this, "Alumno no dado de alta en esta materia","Atención",JOptionPane.ERROR_MESSAGE);
                    this.jtxtMatricula.setText("");
                    this.jtxtMatricula.requestFocus();
                }
                
            }
            
        }
        }
    }//GEN-LAST:event_jtxtMatriculaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtnListo;
    private javax.swing.JLabel jlblBienvenido;
    private javax.swing.JLabel jlblNombre;
    private javax.swing.JTextField jtxtMatricula;
    private javax.swing.JTextField jtxtNombre;
    // End of variables declaration//GEN-END:variables
}
